name: SwiftLint

on:
  pull_request:
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'
  push:
     paths:
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Swiftlint
        run: swiftlint --config sideDishApp/.github/workflows/.swiftlint.yml
